### ISSUE TITLE
Anonymous token is invalid

### ISSUE THREAD

**Issue by vewaclub** [monosans/vk-markovify-chatbot#13]
Запустил код из архива, поставил свой токен в конфиге, при запуске получаю этот текст:
`2023-05-09 21:18:27 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Bot.run_polling() done, defined at C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\bot\bot.py:77> exception=VKAPIError_1116()>
Traceback (most recent call last):
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\bot\bot.py", line 81, in run_polling
    async for event in polling.listen():
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\polling\bot_polling.py", line 57, in listen
    server = await self.get_server()
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\polling\bot_polling.py", line 51, in get_server
    self.group_id = (await self.api.request("groups.getById", {}))["response"][0]["id"]
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\api.py", line 79, in request
    return await self.validate_response(method, data, response)  # type: ignore
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\api.py", line 103, in validate_response
    response = await validator.validate(method, data, response, self)  # type: ignore
  File "C:\Users\ilias\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\response_validator\vk_api_error_validator.py", line 48, in validate
    raise VKAPIError[code](**error)
vkbottle.exception_factory.code_exception.VKAPIError_1116: Anonymous token is invalid`
Генерировал токен по инструкции, все настройки включены

**Comment by monosans** [comment]
Приколы от ВК. Попробуй новый токен создать, вдруг поможет 🙃

**Comment by vewaclub** [comment]
> Приколы от ВК. Попробуй новый токен создать, вдруг поможет 🙃

Все токены нового формата "vk1.****.." выдают такую ошибку, старые токены (пробую от 2022) говорят "invalid access_token (4)"
